Problem 1

Part (c)

In [25]:
import numpy as np
q = 0.4
p = 0.35
s = 0.25

stats = []
for i in range(100000):
    money = 10
    while(money != 0):
        u = np.random.random()
        if u <=q:
            money -= 1
        elif u<= q+p:
            money += 1
        else:
            stats.append(money)
            break
        if money == 0:
            stats.append(money)
print(np.mean(stats))

9.79887


Problem 2

Part (a)

In [ ]:

import math
P = np.zeros((6,6))
for i in range(6):
    for j in range(i+1):
        P[i,j] = math.comb(i,j)*(9/10)**j*(1/10)**(i-j)
P[0] = [0,0,0,0,0,1]
print(P)

[[0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 1.0000e+00]
 [1.0000e-01 9.0000e-01 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00]
 [1.0000e-02 1.8000e-01 8.1000e-01 0.0000e+00 0.0000e+00 0.0000e+00]
 [1.0000e-03 2.7000e-02 2.4300e-01 7.2900e-01 0.0000e+00 0.0000e+00]
 [1.0000e-04 3.6000e-03 4.8600e-02 2.9160e-01 6.5610e-01 0.0000e+00]
 [1.0000e-05 4.5000e-04 8.1000e-03 7.2900e-02 3.2805e-01 5.9049e-01]]


Part (b)

In [13]:
one = np.ones(5)
id = np.identity(5)
q = np.linalg.solve(id-P[1:,1:],one)
print(q[4])

22.171622659565664


Part (c)

In [ ]:
eigval, eigvec = np.linalg.eig(P.T)
index = np.isclose(eigval, 1)
pi = eigvec[:, index][:, 0].real
pi = pi / np.sum(pi)
print(pi)

[0.04315624 0.40960542 0.20480677 0.13651855 0.10052797 0.10538506]
